sudo: required
services: 
  - docker

before_install:
  - docker build -t ramsteven/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ramsteven/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "react-docker"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-058122888301"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"